# Generated by Django 3.0.2 on 2020-06-17 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Gielda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gielda_ogloszenie',
            name='data_dodania',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 16, 40, 53, 660075, tzinfo=utc)),
        ),
    ]
