# Generated by Django 3.0.2 on 2020-03-03 17:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ogloszenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dodania', models.DateTimeField(auto_now=True)),
                ('nazwa', models.CharField(max_length=100)),
                ('termin_dostawy', models.DateTimeField(default='')),
                ('ilość', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)])),
                ('treść', models.TextField()),
                ('konstrukcja', models.CharField(choices=[('aa', 'Fefco 201 (klapówka)'), ('ab', 'Fefco 422 (tacka skladana recznie)'), ('ac', 'Fefco 451 (tacka klejona)'), ('ad', 'Fefco 700 (dno automatyczne)'), ('ae', 'Inne')], default='aa', max_length=30)),
                ('typ_nadruku', models.CharField(choices=[('fl', 'Flexo'), ('of', 'Offset'), ('bz', 'Bez nadruku')], default='bz', max_length=2)),
                ('ilość_kolorów', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=30)),
                ('powierzchnia_zadruku', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('Paleta', models.CharField(choices=[('EU', 'Euro'), ('UK', 'UK'), ('PJ', 'PJ')], default='EU', max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
