# Generated by Django 3.0.2 on 2020-03-10 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogloszenie',
            old_name='nazwa',
            new_name='nazwa_opakowania',
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='długość_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='miejscowość',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='szerokość_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='województwo',
            field=models.CharField(choices=[('BK', '---'), ('DS', 'dolnośląskie'), ('KP', 'kujawsko-pomorskie'), ('LU', 'lubelskie'), ('LB', 'lubuskie'), ('LDZ', 'łódzkie'), ('MP', 'małopolskie'), ('MZ', 'mazowieckie'), ('OP', 'opolskie'), ('PK', 'podkarpackie'), ('PL', 'podlaskie'), ('PM', 'pomorskie'), ('SL', 'śląskie'), ('SK', 'świętokrzyskie'), ('WM', 'warmińsko-mazurskie'), ('WP', 'wielkopolskie'), ('ZP', 'zachodniopomorskie')], default='BK', max_length=30),
        ),
        migrations.AddField(
            model_name='ogloszenie',
            name='wysokość_mm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ogloszenie',
            name='Paleta',
            field=models.CharField(choices=[('EU', 'Paleta EURO'), ('UK', 'Paleta UK'), ('PJ', 'Paleta jednorazowa')], default='EU', max_length=100),
        ),
        migrations.AlterField(
            model_name='ogloszenie',
            name='ilość_kolorów',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='ogloszenie',
            name='powierzchnia_zadruku',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ogloszenie',
            name='treść',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ogloszenie',
            name='typ_nadruku',
            field=models.CharField(choices=[('bz', 'Bez nadruku'), ('fl', 'Flexo'), ('of', 'Offset')], default='bz', max_length=2),
        ),
    ]
